application: mashup-app
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: .*
  script: main.app
  login: required